apiVersion: v1
kind: Pod
metadata:
  name: nginx-example
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.10
    ports: 
      - containerPort: 80
        hostPort: 8084
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.1"
