apiVersion: v1
kind: Service
metadata:
  name: nginx-hello
  labels:
    app: nginx-hello
    tier: frontend
spec:
  ports:
    - port: 8777
      targetPort: 80
      nodePort: 33333
  selector:
    app: nginx-hello
